name: scopify
version: 0.2.2
description: A library for compiling scoped styles
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/scopify
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  csslib: ^0.14.4
  html: ^0.13.3
  meta: ^1.1.5
  source_span: ^1.4.0
  uuid: ^1.0.0
dev_dependencies:
  test: any
